import type { IAlbum } from './type';

export const monsters: IAlbum[] = [
  {
    group: 0,
    id: 0,
    name: 'monstersDirtyBat',
    page: 1,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBatOutofhell',
    page: 1,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDustyBatDungeon',
    page: 2,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFleshGolemDungeon',
    page: 2,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersZombie',
    page: 3,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersUndeadDungeon',
    page: 3,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersFirelog',
    page: 4,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFrostDemon',
    page: 4,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRattlingCobraDungeon',
    page: 5,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersShadowCobra',
    page: 5,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersNuttyNatter',
    page: 6,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSpittleCobra',
    page: 6,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPolarBear',
    page: 7,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersProblemBear',
    page: 7,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBrownBear',
    page: 8,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersInfectedBrownBearDungeon',
    page: 8,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGreenRexDungeon',
    page: 9,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersRedRex',
    page: 9,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGreyRex',
    page: 10,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSnowTroll',
    page: 10,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersNightTrollDungeon',
    page: 11,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMountainTroll',
    page: 11,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersStoneTrollDungeon',
    page: 12,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGreyVulture',
    page: 12,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCultureVulture',
    page: 13,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPackRat',
    page: 13,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersAlbinoRat',
    page: 14,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSewerRatDungeon',
    page: 14,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersForestMuncher',
    page: 15,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSwampMuncherDungeon',
    page: 15,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersNightGhoulDungeon',
    page: 16,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGreyGhoul',
    page: 16,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSwampGhoul',
    page: 17,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSnappingRaptor',
    page: 17,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersJumpingRaptor',
    page: 18,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersRoaringRaptorDungeon',
    page: 18,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBigfootDungeon',
    page: 19,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersYetiDungeon',
    page: 19,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMeanMonsterRabbitDungeon',
    page: 20,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersCholericMonsterRabbit',
    page: 20,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersKillerMonsterRabbit',
    page: 21,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPinkMonsterRabbitDungeon',
    page: 21,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersLunaticMonsterRabbit',
    page: 22,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersToxicMonsterRabbit',
    page: 22,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPirateDarkBeardDungeon',
    page: 23,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSturdySwashbucklerDungeon',
    page: 23,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPirateBloodNoseDungeon',
    page: 24,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersEvilTaurus',
    page: 24,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSulkyTaurus',
    page: 25,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTotalBull',
    page: 25,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersStoneGiantDungeon',
    page: 26,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersLavaGiantDungeon',
    page: 26,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGreenGnoll',
    page: 27,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGreyGnoll',
    page: 27,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRedGnoll',
    page: 28,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGiantSpider',
    page: 28,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTerrorTarantulaDungeon',
    page: 29,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTreeSpider',
    page: 29,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSnowLion',
    page: 30,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTiger',
    page: 30,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPantherDungeon',
    page: 31,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMountainLion',
    page: 31,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHellScorpion',
    page: 32,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersJungleScorpion',
    page: 32,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersShadowScorpion',
    page: 33,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFireScorpionDungeon',
    page: 33,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRedlightSuccubusDungeon',
    page: 34,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSwampNymphomaniac',
    page: 34,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBrideFromHell',
    page: 35,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersWitch',
    page: 35,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBrownCentaur',
    page: 36,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGreenCentaur',
    page: 36,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGreyCentaur',
    page: 37,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBansheeDungeon',
    page: 37,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBitingMutt',
    page: 38,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersIceWolf',
    page: 38,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRabidWolfDungeon',
    page: 39,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGrimWolfDungeon',
    page: 39,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMudBlob',
    page: 40,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSandBlob',
    page: 40,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSlimeBlobDungeon',
    page: 41,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersLavaBlobDungeon',
    page: 41,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBloodthirstyVampire',
    page: 42,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDeviousVampireDungeon',
    page: 42,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSinisterVampire',
    page: 43,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersUglyGremlinDungeon',
    page: 43,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCruelGremlinDungeon',
    page: 44,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGreedyGremlinDungeon',
    page: 44,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGreenishGremlinDungeon',
    page: 45,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDemoralizingDemonDungeon',
    page: 45,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTerrifyingDemon',
    page: 46,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersAbhorrentDemonDungeon',
    page: 46,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBadBanditDungeon',
    page: 47,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersRowdyRobberDungeon',
    page: 47,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersThoughtlessThief',
    page: 48,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBasilisk',
    page: 48,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersFireBasiliskDungeon',
    page: 49,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTwilightAlienDungeon',
    page: 49,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHellAlienDungeon',
    page: 50,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersToxicAlien',
    page: 50,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDarkRiderDungeon',
    page: 51,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFireElementalDungeon',
    page: 51,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGrayGargoyle',
    page: 52,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBrownGargoyle',
    page: 52,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSwampCrocodile',
    page: 53,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFrostAlligator',
    page: 53,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersShadowAlligatorDungeon',
    page: 54,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMudCrocodile',
    page: 54,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersWhiteGorilla',
    page: 55,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersForestGorilla',
    page: 55,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMountainGorilla',
    page: 56,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSkeletonDungeon',
    page: 56,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersVoodooSkeleton',
    page: 57,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersVoodooMasterDungeon',
    page: 57,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSkeletonWarriorDungeon',
    page: 58,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSkeletonSoldierDungeon',
    page: 58,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHorroroftheNight',
    page: 59,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSwampGorgonDungeon',
    page: 59,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersNightGorgon',
    page: 60,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBabyElephant',
    page: 60,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersLion',
    page: 61,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersWildBoar',
    page: 61,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersWildSod',
    page: 62,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersWindElementalDungeon',
    page: 62,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSandstormDungeon',
    page: 63,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBlowflies',
    page: 63,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTerrorTree',
    page: 64,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersToxicTreeDungeon',
    page: 64,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGhostDungeon',
    page: 65,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFireGlompf',
    page: 65,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersWaterGlompfDungeon',
    page: 66,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSwampGlompf',
    page: 66,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCyclingCyclops',
    page: 67,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSandCyclops',
    page: 67,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHellCyclopsDungeon',
    page: 68,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersCaveCyclopsDungeon',
    page: 68,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersOctopusDungeon',
    page: 69,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTimmySuprinoDungeon',
    page: 69,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGrayDragonSpecialQuest',
    page: 70,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDirtyRottenScoundrelDungeon',
    page: 70,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCutthroatDungeon',
    page: 71,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGraveRobberDungeon',
    page: 71,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBlackPhantomDungeon',
    page: 72,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersUnholyMonkDungeon',
    page: 72,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGuyinacowlSpecialQuest',
    page: 73,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDragonofMadnessDungeon',
    page: 73,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDragonofColdDungeon',
    page: 74,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDragonofHellSpecialQuest',
    page: 74,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGiantDragonDungeon',
    page: 75,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSlashingSaurusDungeon',
    page: 75,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSaurusRogueDungeon',
    page: 76,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMountainWarriorSpecialQuest',
    page: 76,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSwampWarriorDungeon',
    page: 77,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheExtraterrestrialDungeon',
    page: 77,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersIllegalAlienSpecialQuest',
    page: 78,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersOutofStateAlienDungeon',
    page: 78,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersLittleGreenManSpecialQuest',
    page: 79,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDragonofDarknessDungeon',
    page: 79,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBlackSkullWarriorDungeon',
    page: 80,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersToxicDragonDungeon',
    page: 80,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSwampDragonDungeon',
    page: 81,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBeastieDungeon',
    page: 81,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersManEaterDungeon',
    page: 82,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersKillingMachineEndgegnerDungeon',
    page: 82,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersKnightoftheBlackSkullEndgegnerDungeon',
    page: 83,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersLordofDarknessEndgegnerDungeon',
    page: 83,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTerribleToxicGremlinEndgegnerDungeon',
    page: 84,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGhostoftheVolcanoEndgegnerDungeon',
    page: 84,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHellBeastEndgegnerDungeon',
    page: 85,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersRobberChiefEndgegnerDungeon',
    page: 85,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersKingSaurusEndgegnerDungeon',
    page: 86,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPirateLeaderEndgegnerDungeon',
    page: 86,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHappySlappytheClownDungeon',
    page: 87,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheBlindKnifeThrowerDungeon',
    page: 87,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMiniatureGnomeDungeon',
    page: 88,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheBeardedLadyDungeon',
    page: 88,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersThePsychoJugglerDungeon',
    page: 89,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSiameseTwinsDungeon',
    page: 89,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBroncotheJokerDungeon',
    page: 90,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheSnakemanDungeon',
    page: 90,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMadameMystiqueDungeon',
    page: 91,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBozotheTerrorClownEndgegnerDungeon',
    page: 91,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRestlessSoulDungeon',
    page: 92,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFuriousSoulDungeon',
    page: 92,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersOldSoulDungeon',
    page: 93,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPestDungeon',
    page: 93,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSoulClumpDungeon',
    page: 94,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersScourgeDungeon',
    page: 94,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHellhoundDungeon',
    page: 95,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheFuehrersHeapDungeon',
    page: 95,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTheDevilsAdvocateDungeon',
    page: 96,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBeelzebossEndgegnerDungeon',
    page: 96,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHobgoblinsboatEndgegnerRaid',
    page: 97,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersStarfishofdeathEndgegnerRaid',
    page: 97,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersNeonyellowdeathEndgegnerRaid',
    page: 98,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTerrorfromthedeepEndgegnerRaid',
    page: 98,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBeastlybratEndgegnerRaid',
    page: 99,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersKingofthedarkdwarvesEndgegnerRaid',
    page: 99,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersInvisiblethreatEndgegnerRaid',
    page: 100,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBiggiethePimpEndgegnerRaid',
    page: 100,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTheCountEndgegnerRaid',
    page: 101,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGoblinmageEndgegnerRaid',
    page: 101,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDjinnEndgegnerRaid',
    page: 102,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersNinjagnomeEndgegnerRaid',
    page: 102,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTitanEndgegnerRaid',
    page: 103,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSuperassassinEndgegnerRaid',
    page: 103,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTheDeadBaronEndgegnerRaid',
    page: 104,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHydraEndgegnerRaid',
    page: 104,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBlindCyclopsEndgegnerRaid',
    page: 105,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersKlomanntheBarbarianEndgegnerRaid',
    page: 105,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCerberusEndgegnerRaid',
    page: 106,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersZombieBerserkerEndgegnerRaid',
    page: 106,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersThethingEndgegnerRaid',
    page: 107,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersCutekittenEndgegnerRaid',
    page: 107,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersArmoreddragonEndgegnerRaid',
    page: 108,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersButtheadEndgegnerRaid',
    page: 108,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCreaturesEndgegnerRaid',
    page: 109,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBathagsEndgegnerRaid',
    page: 109,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDancingogrebrothersEndgegnerRaid',
    page: 110,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersUngorththeMercilessEndgegnerRaid',
    page: 110,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCyberneticzombieEndgegnerRaid',
    page: 111,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersWarogreofwarEndgegnerRaid',
    page: 111,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersArchdemonofconfusionEndgegnerRaid',
    page: 112,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersValkyrieEndgegnerRaid',
    page: 112,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBigmouthofdoomEndgegnerRaid',
    page: 113,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPingPongEndgegnerRaid',
    page: 113,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBoogerustheBoogerGiantEndgegnerRaid',
    page: 114,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersShnivaEndgegnerRaid',
    page: 114,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersAfterDarkorEndgegnerRaid',
    page: 115,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersArmoredfiredragonEndgegnerRaid',
    page: 115,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersWerewolfEndgegnerRaid',
    page: 116,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersCrococopterEndgegnerRaid',
    page: 116,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGripcuttheGhastlyEndgegnerRaid',
    page: 117,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGragoshtheDestroyerEndgegnerRaid',
    page: 117,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRagorththeVengefulEndgegnerRaid',
    page: 118,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSlobbatheMuddEndgegnerRaid',
    page: 118,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersFatElkeEndgegnerRaid',
    page: 119,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersThemotherinlawEndgegnerRaid',
    page: 119,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersReapermanEndgegnerRaid',
    page: 120,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDebuggersDoomEndgegnerRaid',
    page: 120,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersAIEndgegnerRaid',
    page: 121,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersThebossEndgegnerRaid',
    page: 121,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHellgoretheHellishDungeon',
    page: 122,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHenrytheMagicFairyDungeon',
    page: 122,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersJetthePantyRaiderDungeon',
    page: 123,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersClappervanHellsingDungeon',
    page: 123,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTheKOmaKOmmanderDungeon',
    page: 124,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersRoughiantheRuthlessDungeon',
    page: 124,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBentheMarketeerDungeon',
    page: 125,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHectortheContractorDungeon',
    page: 125,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMotuwithaClubDungeon',
    page: 126,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersJacktheHammererEndgegnerDungeon',
    page: 126,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersLivingCakeManTurmEtage',
    page: 127,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGreenFairyDrinkerbellTurmEtage',
    page: 127,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTinvalidTurmEtage',
    page: 128,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHarmlessTeddyBearTurmEtage',
    page: 128,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersFlowerlinaTurmEtage',
    page: 129,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersToothFairyTurmEtage',
    page: 129,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersUglyChickTurmEtage',
    page: 130,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersWarblingBirdieTurmEtage',
    page: 130,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersWellMeaningFairyTurmEtage',
    page: 131,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTrickeribooksCheatinchildTurmEtage',
    page: 131,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSingingDumplingTurmEtage',
    page: 132,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPuppeteersRightTurmEtage',
    page: 132,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGrinningCatTurmEtage',
    page: 133,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersAmbitiousFrogTurmEtage',
    page: 133,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPinociwhatsitTurmEtage',
    page: 134,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersxWishesTurmEtage',
    page: 134,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBootleggedPussTurmEtage',
    page: 135,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDottyfromKansasTurmEtage',
    page: 135,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTheLastAirgazerTurmEtage',
    page: 136,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersARabbitandaHedgehogTurmEtage',
    page: 136,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHolgerNilssonTurmEtage',
    page: 137,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHighSpiritedGhostTurmEtage',
    page: 137,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBloodRedRidingHoodTurmEtage',
    page: 138,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSnowflakeTurmEtage',
    page: 138,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersStarMoneyTurmEtage',
    page: 139,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMissMatchTurmEtage',
    page: 139,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersIceQueenTurmEtage',
    page: 140,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBadlyRaisedBoysTurmEtage',
    page: 140,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersLambikinsandFishyTurmEtage',
    page: 141,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDonkeyShotTurmEtage',
    page: 141,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersStreetThiefwithMonkeyTurmEtage',
    page: 142,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersAliceinWonderTurmEtage',
    page: 142,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPenterabbitTurmEtage',
    page: 143,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDynamicPeterTurmEtage',
    page: 143,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersFoolishPrincessTurmEtage',
    page: 144,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPleasureAddictTurmEtage',
    page: 144,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersAmnastasiaRubliovkaTurmEtage',
    page: 145,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersUselessLivestockTurmEtage',
    page: 145,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHumptyDumptyTurmEtage',
    page: 146,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersKingChinbeardTurmEtage',
    page: 146,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSandmanTurmEtage',
    page: 147,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersJohnorTomTurmEtage',
    page: 147,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersScarecrowTurmEtage',
    page: 148,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMirroredFoolTurmEtage',
    page: 148,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersThreeLittlePigsTurmEtage',
    page: 149,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGooseinLuckTurmEtage',
    page: 149,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSimplemindedChickenThiefTurmEtage',
    page: 150,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBabaYagaTurmEtage',
    page: 150,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMerlinTurmEtage',
    page: 151,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersJulioandRomyTurmEtage',
    page: 151,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPrinceinShepherdsSkinTurmEtage',
    page: 152,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersRobintheRedistributorTurmEtage',
    page: 152,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersAlitheSesameOpenerTurmEtage',
    page: 153,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFreshlyDressedEmperorTurmEtage',
    page: 153,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDumboTurmEtage',
    page: 154,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHanselandGretelTurmEtage',
    page: 154,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBearFearTurmEtage',
    page: 155,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPokerhontasTurmEtage',
    page: 155,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMassFlyMurdererTurmEtage',
    page: 156,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersCinderellaTurmEtage',
    page: 156,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTheEnchantingGenieTurmEtage',
    page: 157,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBronycornTurmEtage',
    page: 157,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHuldatheCloudFairyTurmEtage',
    page: 158,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersLeprechoreTurmEtage',
    page: 158,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRobberHopsenplopsTurmEtage',
    page: 159,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersThornyLionTurmEtage',
    page: 159,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersAquirellatheDazzlerTurmEtage',
    page: 160,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPrinceCharmingTurmEtage',
    page: 160,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBOWolfTurmEtage',
    page: 161,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPetertheWolfTurmEtage',
    page: 161,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBeautifulPrincessTurmEtage',
    page: 162,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFearlessWandererTurmEtage',
    page: 162,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRedWhiteForeverTurmEtage',
    page: 163,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFriendlySnowmanTurmEtage',
    page: 163,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersParsifalTurmEtage',
    page: 164,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBrotherBarflyTurmEtage',
    page: 164,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersKingArthurTurmEtage',
    page: 165,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSigiMuscleheadTurmEtage',
    page: 165,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersThePiedPiperofJamelinTurmEtage',
    page: 166,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheGuysfromOzTurmEtage',
    page: 166,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersLittleJohnTurmEtage',
    page: 167,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheEasterBunnyTurmEtage',
    page: 167,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHoneyRobbearTurmEtage',
    page: 168,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersShirktheOgreTurmEtage',
    page: 168,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCozyBearTurmEtage',
    page: 169,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersNumberNipTurmEtage',
    page: 169,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersThreeHungryBearsTurmEtage',
    page: 170,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSevenHostagesTurmEtage',
    page: 170,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSevenDwarfsTurmEtage',
    page: 171,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersRespectableDragonSlayerTurmEtage',
    page: 171,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDucatDonkeyTurmEtage',
    page: 172,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBeanCounterTurmEtage',
    page: 172,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHappyDragonTurmEtage',
    page: 173,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersShockheadedJackTurmEtage',
    page: 173,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPapaFrostTurmEtage',
    page: 174,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDreamCoupleTurmEtage',
    page: 174,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersThreeGhostsTurmEtage',
    page: 175,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSleepyPrincessTurmEtage',
    page: 175,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersNanobotPorridgeTurmEtage',
    page: 176,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBarbpunzelTurmEtage',
    page: 176,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPricklyBeastGildenportal',
    page: 177,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersRottenCrowGildenportal',
    page: 177,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSkinnySkeletonGildenportal',
    page: 178,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersCellarZombieGildenportal',
    page: 178,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHornedOneGildenportal',
    page: 179,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersToppledOneGildenportal',
    page: 179,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBloodlustyButcherGildenportal',
    page: 180,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDarkArcherGildenportal',
    page: 180,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersLanceStrongarmGildenportal',
    page: 181,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFemmeFatarielGildenportal',
    page: 181,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBadBatGildenportal',
    page: 182,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSabertoothedKittyGildenportal',
    page: 182,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSandRoachGildenportal',
    page: 183,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMummedMummyGildenportal',
    page: 183,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPlunderblarghGildenportal',
    page: 184,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSnailingGildenportal',
    page: 184,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSlashingSerpentGildenportal',
    page: 185,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersQuadroslayerGildenportal',
    page: 185,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersLambentLimbeaterGildenportal',
    page: 186,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTorturielGildenportal',
    page: 186,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersLittleBadgererGildenportal',
    page: 187,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBigBadgererGildenportal',
    page: 187,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTerrifyingToadGildenportal',
    page: 188,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBnDemonGildenportal',
    page: 188,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGogglyBeastGildenportal',
    page: 189,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersClubberGildenportal',
    page: 189,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRecklessReaperGildenportal',
    page: 190,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersEightleggedArachnidGildenportal',
    page: 190,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDeepPriestGildenportal',
    page: 191,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMephissimoGildenportal',
    page: 191,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBottomcreeperGildenportal',
    page: 192,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersEvilEnchantressGildenportal',
    page: 192,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRuminantGildenportal',
    page: 193,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersOldPurplehandGildenportal',
    page: 193,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMegaBalrogGildenportal',
    page: 194,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersArchfallenGildenportal',
    page: 194,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPhantastotheBlacksmithGildenportal',
    page: 195,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGreatUncleofUntidinessGildenportal',
    page: 195,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTerribleTinkererGildenportal',
    page: 196,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersVariabloGildenportal',
    page: 196,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersImpulsiveImpGildenportal',
    page: 197,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHenchdemonGildenportal',
    page: 197,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHorroronIceGildenportal',
    page: 198,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFuriousFuryGildenportal',
    page: 198,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersFlayerGildenportal',
    page: 199,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersStomperGildenportal',
    page: 199,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBloodthirstyBaronGildenportal',
    page: 200,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBrainLeechGildenportal',
    page: 200,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersExecutorGildenportal',
    page: 201,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersEvilEelGildenportal',
    page: 201,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBeastSpielerportal',
    page: 202,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHunchbackedZombieSpielerportal',
    page: 202,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersFullDuplexZombieSpielerportal',
    page: 203,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersThornyDevourerSpielerportal',
    page: 203,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSinisterSmasherSpielerportal',
    page: 204,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersUnspeakableSpielerportal',
    page: 204,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCorpusEruptusSpielerportal',
    page: 205,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMasterfulMassacristSpielerportal',
    page: 205,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersEightLeggedArianeSpielerportal',
    page: 206,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersKingKnuckelboneSpielerportal',
    page: 206,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRitualistSpielerportal',
    page: 207,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDesertDevourerSpielerportal',
    page: 207,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSnakerSpielerportal',
    page: 208,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSnakeMageSpielerportal',
    page: 208,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGoryGathererSpielerportal',
    page: 209,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersLithicLeviathanSpielerportal',
    page: 209,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGhastlyGreySpielerportal',
    page: 210,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMaliciousMarthaSpielerportal',
    page: 210,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBigZSpielerportal',
    page: 211,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFatherofLiesSpielerportal',
    page: 211,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSpikeySpitefulSpielerportal',
    page: 212,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHellmuttSpielerportal',
    page: 212,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSoldierofDoomSpielerportal',
    page: 213,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBloodOccultistSpielerportal',
    page: 213,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBitingBatbuckSpielerportal',
    page: 214,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHisPestilenceSpielerportal',
    page: 214,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersObstructorSpielerportal',
    page: 215,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMartyrdomsMaidenSpielerportal',
    page: 215,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMuscularMuzzleSpielerportal',
    page: 216,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersAzmoFantasmoSpielerportal',
    page: 216,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPrematureHellspawnSpielerportal',
    page: 217,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersAngelofPainSpielerportal',
    page: 217,
  },
  {
    group: 0,
    id: 0,
    name: 'monstershxxrSpielerportal',
    page: 218,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersLoricateBiterSpielerportal',
    page: 218,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSlenderPersonSpielerportal',
    page: 219,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHammererSpielerportal',
    page: 219,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHorrendousHagSpielerportal',
    page: 220,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDeeplyFallenSpielerportal',
    page: 220,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDemonofTerrorSpielerportal',
    page: 221,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersExitusPrimeSpielerportal',
    page: 221,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBruteSpielerportal',
    page: 222,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersNastyTrapperSpielerportal',
    page: 222,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersExecutorSpielerportal',
    page: 223,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFattyontheRocksSpielerportal',
    page: 223,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersExExorcistSpielerportal',
    page: 224,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDeathDispenserSpielerportal',
    page: 224,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersShadowofPowerSpielerportal',
    page: 225,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHornedWitchSpielerportal',
    page: 225,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDeathsBestBuddySpielerportal',
    page: 226,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersDevourerofSoulsSpielerportal',
    page: 226,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersRobertDrunkatheonDungeon',
    page: 227,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersLeftyLennisterDungeon',
    page: 227,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPetyrthePimpDungeon',
    page: 228,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHolundorDungeon',
    page: 228,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDrogotheThreateningDungeon',
    page: 229,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheGingerSlowwormDungeon',
    page: 229,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersQueenMotherDungeon',
    page: 230,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheMiniaturePoodleDungeon',
    page: 230,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTheRidingMountainrangeDungeon',
    page: 231,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersJoffreytheKidDespotDungeon',
    page: 231,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCoolVillainDungeon',
    page: 232,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersBrygitteDungeon',
    page: 232,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSnowmanandShadowWolfDungeon',
    page: 233,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheWomaninRedDungeon',
    page: 233,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBoyishBrienneDungeon',
    page: 234,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersRamsaytheDegraderDungeon',
    page: 234,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersFacelessDungeon',
    page: 235,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersViciousGnomeDungeon',
    page: 235,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTheProtectorDungeon',
    page: 236,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheHardtoBurnDungeon',
    page: 236,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersEloquentHatDungeon',
    page: 237,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSourArgusDungeon',
    page: 237,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersFluffyFriendDungeon',
    page: 238,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersAvanBlameDungeon',
    page: 238,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPhonyLockyDungeon',
    page: 239,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersKillerStareDungeon',
    page: 239,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBadKisserDungeon',
    page: 240,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersGuardianoftheGoldenEggDungeon',
    page: 240,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGentleGiantDungeon',
    page: 241,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPedigreeBadBoyDungeon',
    page: 241,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersUnrepentantPenitentDungeon',
    page: 242,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheGiftedOneandRonDungeon',
    page: 242,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersStumbledoorDungeon',
    page: 243,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPeteyRatDungeon',
    page: 243,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDiabolicalDoloresDungeon',
    page: 244,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersInconvenientlyInfiniteInferiDungeon',
    page: 244,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBellatheBeastlyDungeon',
    page: 245,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersLuciusthePureBloodDungeon',
    page: 245,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCutsieCuddlerDungeon',
    page: 246,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersYouShouldKnowWhoDungeon',
    page: 246,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersOrconWargDungeon',
    page: 247,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTrollTrioDungeon',
    page: 247,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersTheKingDungeon',
    page: 248,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSmollumDungeon',
    page: 248,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSpidersagainDungeon',
    page: 249,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersOrcBossDungeon',
    page: 249,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersBezogDungeon',
    page: 250,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSmoulderDungeon',
    page: 250,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersNazgulsNazgulsesDungeon',
    page: 251,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMonsterintheLakeDungeon',
    page: 251,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersValaraukarDungeon',
    page: 252,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersUrcsitheUrukDungeon',
    page: 252,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersPrompterSplittongueDungeon',
    page: 253,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSamowarthePaleDungeon',
    page: 253,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersOliphauntTamerDungeon',
    page: 254,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersUndeadArmyDungeon',
    page: 254,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersShelantulaDungeon',
    page: 255,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersRuleroftheNineDungeon',
    page: 255,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersMauronsMawDungeon',
    page: 256,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersTheNecromancerDungeon',
    page: 256,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersDoctorBenxDungeon',
    page: 257,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersZakrebleDungeon',
    page: 257,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGoldenGianpyDungeon',
    page: 258,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersWillyrexDungeon',
    page: 258,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersAlvaroDungeon',
    page: 259,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPaulTerraDungeon',
    page: 259,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSpieletrendDungeon',
    page: 260,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersFattyPillowDungeon',
    page: 260,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersGimperDungeon',
    page: 261,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersUngeDungeon',
    page: 261,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHeimdallDungeon',
    page: 262,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersValkyriesDungeon',
    page: 262,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHelDungeon',
    page: 263,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersThorDungeon',
    page: 263,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersOdinDungeon',
    page: 264,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersLokiDungeon',
    page: 264,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersYmirDungeon',
    page: 265,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMidgardSerpentDungeon',
    page: 265,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersFenrisWolfDungeon',
    page: 266,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersSurtrDungeon',
    page: 266,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersSingingSirensDungeon',
    page: 267,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPolyphemustheCyclopsDungeon',
    page: 267,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersCerberusDungeon',
    page: 268,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersMedusaDungeon',
    page: 268,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersAthenaDungeon',
    page: 269,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersHerculesDungeon',
    page: 269,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersAresDungeon',
    page: 270,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersPoseidonDungeon',
    page: 270,
  },
  {
    group: 0,
    id: 0,
    name: 'monstersHadesDungeon',
    page: 271,
  },
  {
    group: 1,
    id: 0,
    name: 'monstersZeusDungeon',
    page: 271,
  },
];
